# Generated by Django 4.2.25 on 2025-10-06 14:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import game.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('code', models.CharField(default=game.models.short_code, max_length=8, unique=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('deadline_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('current_order', models.PositiveIntegerField(default=1)),
                ('score', models.IntegerField(default=100)),
                ('letters', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('role', models.CharField(choices=[('A', 'Alex'), ('B', 'Noa')], max_length=1)),
                ('is_host', models.BooleanField(default=False)),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='game.team')),
            ],
        ),
    ]
