# Generated by Django 4.2.25 on 2025-10-07 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puzzle_slug', models.CharField(max_length=32)),
                ('code', models.CharField(max_length=32)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codes', to='game.team')),
            ],
            options={
                'unique_together': {('team', 'puzzle_slug')},
            },
        ),
    ]
