# Generated by Django 4.2.25 on 2025-10-09 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_teamcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='hotel_solved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='team',
            name='museum_solved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='team',
            name='rail_solved',
            field=models.BooleanField(default=False),
        ),
    ]
